[connections.snowflake]
account = "YHCVIOD-XWB90052"
user = "jessicasandagorda"
password='35261464Color!'
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
